services:
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config-db.sql:/docker-entrypoint-initdb.d/config-db.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - internal_network

  app:
    image: app
    build: .
    networks:
      - internal_network
    environment:
      ConnectionStrings__LyMarketDatabase: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_BASE_URL_OBJECT: ${AWS_BASE_URL_OBJECT}
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
    depends_on:
      - app
    networks:
      - internal_network

volumes:
  db-data:

networks:
  internal_network:
