version: "3.8"

services:
  app:
    image: app
    build: .
    networks:
      - internal_network
    environment:
      ConnectionStrings__LyMarketDatabase: "Host=database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ASPNETCORE_URLS: http://*:8080
      ASPNETCORE_HTTPS_PORT: https://*:8081
      ASPNETCORE_ENVIRONMENT: Development

  database:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal_network

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - internal_network

volumes:
  database:

networks:
  internal_network:
