version: "3.8"

services:
  app:
    build: .
    networks:
      - internal_network
  nginx:
    build:
      context: ./nginx # Đường dẫn tới thư mục chứa Dockerfile của nginx
      dockerfile: Dockerfile # Tên của tệp Dockerfile
    ports:
      - "80:9999"
    depends_on:
      - app
    networks:
      - internal_network

networks:
  internal_network:
