version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Create a Dockerfile in your app folder if you don't have one already
    ports:
      - "8000:80" # Map host port 8000 to container port 80

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
