version: "3"

tasks:
  build_dev:
    cmds:
      - docker compose --env-file .env.dev build
  build_prod:
    cmds:
      - docker compose -f docker-compose.prod.yml --env-file .env.prod build
  up_dev:
    cmds:
      - docker compose --env-file .env.dev up --build -d
  down_dev:
    cmds:
      - docker compose --env-file .env.dev down
  up_prod:
    cmds:
      - docker compose -f docker-compose.prod.yml --env-file .env.prod up --build -d
  down_prod:
    cmds:
      - docker compose -f docker-compose.prod.yml --env-file .env.prod down
  restart_app:
    cmds:
      - docker compose restart app-1

  clean_db:
    cmds:
      - docker compose down -v
      - docker compose up db -d
      - task: watch

  create-migration:
    cmds:
      - dotnet ef migrations add "init" --context VsbgDbContext --project ./Vsbg.Infrastructure --startup-project ./Vsbg.WebApi
  update-migration:
      - dotnet ef database update --context VsbgDbContext --verbose --project ./Vsbg.Infrastructure --startup-project ./Vsbg.WebApi
  # Local Enviroment
  reset-migrations-local:
    cmds:
      - rm -rf ./Vsbg.Infrastructure/Migrations
      - task: create-migration
      - docker compose down -v
      - docker compose up db -d
      - task: update-migration
  watch:
    cmd: export DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1 && dotnet watch --project SI-BE
